baseURL: http://slackerethos.com/
languageCode: en-us
title: The Slacker Ethos
theme: PaperMod
paginate: 5
enableRobotsTXT: true
googleAnalytics: G-53845PPRLP

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: The Slacker Ethos
  description: "On simplicity, funemployment, and the virtue of laziness"
  keywords: [Blog, Portfolio, PaperMod]
  author: Kosi
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: true
  ShowReadingTime: false
  ShowShareButtons: true
  ShareButtons: ["twitter", "reddit", "facebook"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false

  homeInfoParams:
    Title: "The Slacker Ethos &#x1F4A1;"
    Content: |
      "For instance, on the planet Earth, man had always assumed that he was more intelligent than dolphins because he had achieved so much — the wheel, New York, wars and so on — whilst all the dolphins had ever done was muck about in the water having a good time. But conversely, the dolphins had always believed that they were far more intelligent than man — for precisely the same reasons.”
      
      &#x1F42C;  *The Hitchhiker's Guide to the Galaxy* by Douglas Adams

  socialIcons:
    - name: twitter
      url: "https://twitter.com/artofease"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 10
    - identifier: about
      name: about
      url: /about/
      weight: 20